poling/urls.py
from django.urls import path

from . import views as view

app_name = 'poling'
urlpatterns = [
	# /polls
    path('', view.IndexView.as_view(), name='index'),
    # /polls/5
    path('<int:pk>/', view.DetailView.as_view(), name='detail'),
    # /polls/5/results
    path('<int:pk>/results/', view.ResultsView.as_view(), name='results'),
    # /polls/5/vote
    path('<int:question_id>/vote/', view.vote, name='vote'),

]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poling.urls')),
]

poling/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('Date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	#Column header for was_published_recently
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def  __str__(self):
		return self.choice_text

poling/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question
# Create your views here.

class IndexView(generic.ListView):
	template_name = 'poling/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""
		Excludes any questions that aren't published yet.
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())

class DetailView(generic.DetailView):
	model = Question
	template_name = 'poling/detail.html'


class ResultsView(generic.DetailView):
	model = Question
	template_name = 'poling/results.html'
		

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		#Redisplay the question voting form
		context = {
			'question': question,
			'erro_message': "You didn't select a choice",
		}
		return render(request, 'poling/detail.html', context)

	else:
		selected_choice.votes += 1
		selected_choice.save()

		return HttpResponseRedirect(reverse('poling:results', args=(question.id,)))

poling/templates/poling/detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'poling/style.css'%}">
</head>
<body>
	<div class="container">
		<div class="text-center">	
	    	<h2>{{ question.question_text }}</h2>
		</div>

{% if error_messsage %}<p><strong>{{ error_message }}</strong></p>{% endif%}
		<form action="{% url 'poling:vote' question.id %}" method="post">
		<div class="row justify-content-md-center">
{% csrf_token %}
{% for choice in question.choice_set.all %}
				<div class="col-12 col-sm-6 col-md-8">
					<div class="card">
					  <div class="list-group list-group-flush">
					    <div class="list-group-item">			    	
							<div class="form-check">			
								<input  class="form-check-input" type="radio" name="choice" id="choice{{ forloop.couter }}" value="{{ choice.id }}">
								<label  class="form-check-label" for="choice {{ forloop.couter }}">{{ choice.choice_text }}
								</label>
							</div>
					    </div>
					  </div>
					</div>
				</div>
{% endfor %}
				<div class="col-12 col-sm-6 col-md-8">
					<button class="btn btn-primary" type="submit" name="Vote">Vote</button>				
				</div>
		</div>
		</form>


	</div>
</body>
</html>

poling/templates/poling/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'poling/style.css'%}">
</head>
<body>
	<div class="container">
		<div class="text-center">	
			<img class="d-block mx-auto mb-4" width="72" height="72" src="{% static 'poling/images/Polling-icon.png'%}">
			<h2>Poling seputar Teknologi</h2>
		</div>
		<div class="row justify-content-md-center">
		{% if latest_question_list %}
			{% for question in latest_question_list %}
			<div class="col-md-3">
				<div class="card">
					<div class="card-body">
						<h5 class="card-title">{{question.question_text }}</h5>
						<a href="{% url 'poling:results' question.id %}" class="card-link">Results</a>
						<a href="{% url 'poling:detail' question.id %}" class="card-link">Votes</a>
					</div>
				</div>
			</div>
			{% endfor %}
		{% else %}
			<p>No polls are avaliable.</p>
		{% endif %}
		</div>
	</div>
</body>
</html>

poling/templates/poling/results.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'poling/style.css'%}">
</head>
<body>
	<div class="container">
		<div class="text-center">	
			<h2>{{ question.question_text }}</h2>
		</div>
		<div class="row justify-content-md-center">
{% for choice in question.choice_set.all %}
			<div class="col-12 col-sm-6 col-md-8">
				<div class="card">
				  <div class="list-group list-group-flush">
				    <div class="list-group-item">			    	
					    <h5 class="card-title">	{{ choice.choice_text }}</h5>
					    <p class="card-text">{{ choice.votes }} Votes</p>
					   	<div class="progress progress-xs bg-transparent" style="height: 2px;">
							<div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="{{ choice.votes }}" aria-valuemin="0" aria-valuemax="10" style="width: {{ choice.votes }}%"></div>
						</div>
				    </div>
				  </div>
				</div>
			</div>
{%endfor%}
		</div>
		<div class="text-center">
			<a href="{% url 'poling:detail' question.id %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Vote again</a>
		</div>
	</div>
</body>